{{- if and .Values.imagePullSecret.create (eq (include "alquimia.helmSecrets" .) "true") }}
{{- $auth := printf "%s:%s" .Values.imagePullSecret.username .Values.imagePullSecret.password | b64enc }}
{{- $dockerconfig := dict "auths" (dict .Values.imagePullSecret.server (dict "username" .Values.imagePullSecret.username "password" .Values.imagePullSecret.password "auth" $auth)) | toJson | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ include "alquimia.namespace" . }}
  labels:
    {{- include "alquimia.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfig }}
{{- end }}
