{{- if and .Values.runtime.enabled (gt (int .Values.runtime.workerReplicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alquimia-runtime-worker
  namespace: {{ include "alquimia.namespace" . }}
  labels:
    app: alquimia-runtime
    role: worker
    {{- include "alquimia.labels" . | nindent 4 }}
spec:
  minAvailable: {{ min 2 (sub (int .Values.runtime.workerReplicas) 1) }}
  selector:
    matchLabels:
      app: alquimia-runtime
      app.kubernetes.io/part-of: alquimia
      role: worker
{{- end }}
