{{- if and (eq (.Values.secrets.backend | default "sealed") "sealed") .Values.sealedSecrets }}
{{- range $name, $secret := .Values.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}
  namespace: {{ include "alquimia.namespace" $ }}
  labels:
    {{- include "alquimia.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    {{- range $key, $val := $secret.encryptedData }}
    {{ $key | quote }}: {{ $val | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ $name }}
      namespace: {{ include "alquimia.namespace" $ }}
      labels:
        {{- include "alquimia.labels" $ | nindent 8 }}
    type: {{ $secret.type | default "Opaque" }}
{{- end }}
{{- end }}
